classes:
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.ubuntu
parameters:
  _param:
    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 172.16.10.100
    infra_config_deploy_address: 192.168.10.90

    cluster_domain: k8s-ha-contrail.local
    cluster_name: k8s-ha-contrail
    apt_mk_version: nightly
  linux:
    network:
      host:
        self:
          address: ${_param:single_address}
          names:
          - ${linux:system:name}
          - ${linux:system:name}.${linux:system:domain}
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
