classes:
- system.linux.system.repo.ubuntu
- system.linux.system.repo.mcp.salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.salt.minion.cert.k8s_server
- system.reclass.storage.salt
- system.reclass.storage.system.kubernetes_control_cluster
- cluster.k8s-ha-calico-syndic
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/ohryhorov/mcp-virtual-lab"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$WV0P1shnoDh2gI/Z$22/Bcd7ffMv0jDlFpT63cAU4PiXHz9pjXwngToKwqAsgoeK4HNR3PiKaushjxp3JsQ8hNoJmAC6TxzVqfV8WH/"
    salt_master_host: 127.0.0.1
  salt:
    master:
      worker_threads: 40
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
      environment:
        prd:
          formula:
            reclass:
              source: git
              address: 'https://github.com/ohryhorov/salt-formula-reclass'
              revision: master
              module:
                reclass.py: reclass.py
              state:
                reclass.py: reclass.py 
            salt:
              source: git
              address: 'https://github.com/ohryhorov/salt-formula-salt'
              revision: master
              module:
                modelschema.py: modelschema.py
                modelutils.py: modelutils.py
                saltkey.py: saltkey.py
                saltresource.py: saltresource.py
                seedng.py: seedng.py
                virtng.py: virtng.py
              state:
                httpng.py: httpng.py
  reclass:
    storage:
      class_mapping:
        common_node:
          expression: all
          node_param:
            single_address:
              value_template: <<node_control_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
        infra_config:
          expression:
          - <<node_hostname>>__startswith__cfg
          - <<node_cluster>>__equals__k8s-ha-calico-syndic
          cluster_param:
            infra_config_address:
              value_template: <<node_control_ip>>
            infra_config_deploy_address:
              value_template: <<node_deploy_ip>>
            cluster_domain:
              value_template: <<node_domain>>
        kubernetes_control01:
          expression:
          - <<node_hostname>>__equals__ctl01
          - <<node_cluster>>__equals__k8s-ha-calico-syndic
          cluster_param:
            kubernetes_control_node01_address:
              value_template: <<node_control_ip>>
        kubernetes_control02:
          expression:
          - <<node_hostname>>__equals__ctl02
          - <<node_cluster>>__equals__k8s-ha-calico-syndic
          cluster_param:
            kubernetes_control_node02_address:
              value_template: <<node_control_ip>>
        kubernetes_control03:
          expression:
          - <<node_hostname>>__equals__ctl03
          - <<node_cluster>>__equals__k8s-ha-calico-syndic
          cluster_param:
            kubernetes_control_node03_address:
              value_template: <<node_control_ip>>
        kubernetes_compute:
          expression:
          - <<node_hostname>>__startswith__cmp
          - <<node_cluster>>__equals__k8s-ha-calico-syndic
          node_class:
            value_template:
              - cluster.<<node_cluster>>.kubernetes.compute

