classes:
- system.linux.system.repo.ubuntu
- system.openssh.client.lab
- system.salt.master.single
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.mysql.client
- system.reclass.storage.salt
- system.reclass.storage.system.infra_idm_cluster
- cluster.aaa_ha_freeipa.infra
- cluster.aaa_ha_freeipa.aaa
- cluster.aaa_ha_freeipa
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://gerrit.mcp.mirantis.net/salt-models/mcp-virtual-lab.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$WV0P1shnoDh2gI/Z$22/Bcd7ffMv0jDlFpT63cAU4PiXHz9pjXwngToKwqAsgoeK4HNR3PiKaushjxp3JsQ8hNoJmAC6TxzVqfV8WH/"
    salt_master_host: 127.0.0.1
  salt:
    master:
      enabled: true
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
  reclass:
    storage:
      class_mapping:
        common_node:
          expression: all
          node_param:
            single_address:
              value_template: <<node_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
        infra_config:
          expression: <<node_hostname>>__startswith__cfg
          cluster_param:
            infra_config_address:
              value_template: <<node_ip>>
            infra_config_deploy_address:
              value_template: <<node_ip>>
        identity_control01:
          expression: <<node_hostname>>__equals__idm01
          cluster_param:
            identity_control_node01_address:
              value_template: <<node_ip>>
          node_class:
            value_template:
              #- system.linux.system.repo.saltstack.rhel7
              - cluster.<<node_cluster>>.aaa.freeipa_server
        identity_control02:
          expression: <<node_hostname>>__equals__idm02
          cluster_param:
            identity_control_node02_address:
              value_template: <<node_ip>>
          node_class:
            value_template:
              #- system.linux.system.repo.saltstack.rhel7
              - cluster.<<node_cluster>>.aaa.freeipa_server
        identity_control03:
          expression: <<node_hostname>>__equals__idm03
          cluster_param:
            identity_control_node03_address:
              value_template: <<node_ip>>
          node_class:
            value_template:
              #- system.linux.system.repo.saltstack.rhel7
              - cluster.<<node_cluster>>.aaa.freeipa_server
        identity_client:
          expression: <<node_hostname>>__startswith__tst
          node_class:
            value_template:
              - system.linux.system.repo.ubuntu
              - cluster.<<node_cluster>>.aaa.freeipa_client
