parameters:
  _param:
    cluster_domain: drivetrain-ha-clusters.local
    cluster_name: drivetrain-ha-clusters
    apt_mk_version: nightly
    admin_email: root@localhosti
    infra_config_hostname: cfg01
    infra_config_address: 172.16.10.100
    infra_config_deploy_address: 192.168.10.90
    salt_minion_ca_host: ci01.${_param:cluster_domain}
    salt_minion_ca_authority: salt_master_ca
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
